### ISSUE TITLE
Doesn't work - Adrenaline 6.61 - Henkaku Enso on Firmware 3.60

### ISSUE THREAD

**Issue by knerlington** [isage/adrenaline_usb_enabler#1]
This plugin is exactly what I was looking for today, but I can't get it to work.

The file is located under ur0:tai/ and referenced in ur0:tai/config.txt as "ur0:tai/adrenaline_usb_enabler.suprx" under a manually added "*ALL" section. There's a forward slash in the path in the install instructions which I assume is a typo? Since every other user plugin is prefixed with "ur0:tai" in the config.

I've reloaded the config from the henkaku settings and tried rebooting, but when I connect via USB in adrenaline I get the same old error as always.

**Comment by isage** [comment]
Screenshot/photo plz

**Comment by knerlington** [comment]
I promise that the install location and the config path is exactly what I wrote in the issue. 
I did point out the path error from the install instructions after all. I also for the sake of it tried with the incorrect extra forward slash in the config.

- No accidental/hidden spaces in the path for the plugin
- Plugin is installed under "ur0:tai" where I have all my other working plugins
- config.txt = "ur0:tai/adrenaline_usb_enabler.suprx" under "*ALL" (tried lowercase in case it's case sensitive as well)
- 80244114 error in adrenaline when attempting to use USB
- Reloaded the config from henkaku settings and rebooted the console

**Comment by isage** [comment]
Fine, if you don't wanna provide a photo of the error then atleast write down when you get that error. And in what game.

**Comment by knerlington** [comment]
No need to be upset. Busted camera that's all. It's the 80244114 error in adrenaline from above. Tried in MGS Peace Walker when using the "tranfarring" feature. Is that the thing; Peace Walker using a mass storage copy feature and the plugin only allowing a form of device recognition? 

EDIT:
Ok just found a reddit post about this saying it's not related to the "USB connection" found in XMB and only from within games.
That should really be stated/changed in the description since the plugin name and current desc. in that case is rather misleading.
If that is indeed the case you can close the issue.

Cheers!

**Comment by isage** [comment]
Plugin is only for pspcm, yes. Not mass storage.
